#if !defined(AFX_ADXFUNCTION_H__810B1D8A_D077_4A26_B55A_1AA3D6F044C6__INCLUDED_)
#define AFX_ADXFUNCTION_H__810B1D8A_D077_4A26_B55A_1AA3D6F044C6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeries;

/////////////////////////////////////////////////////////////////////////////
// CADXFunction wrapper class

class CADXFunction : public COleDispatchDriver
{
public:
	CADXFunction() {}		// Calls COleDispatchDriver default constructor
	CADXFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CADXFunction(const CADXFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CSeries GetDMDown();
	CSeries GetDMUp();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ADXFUNCTION_H__810B1D8A_D077_4A26_B55A_1AA3D6F044C6__INCLUDED_)
