#if !defined(AFX_EMBOSSFILTER_H__4436E67E_107B_492F_9B3C_EFF6D6B1D848__INCLUDED_)
#define AFX_EMBOSSFILTER_H__4436E67E_107B_492F_9B3C_EFF6D6B1D848__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEmbossFilter wrapper class

class CEmbossFilter : public COleDispatchDriver
{
public:
	CEmbossFilter() {}		// Calls COleDispatchDriver default constructor
	CEmbossFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CEmbossFilter(const CEmbossFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EMBOSSFILTER_H__4436E67E_107B_492F_9B3C_EFF6D6B1D848__INCLUDED_)
