#if !defined(AFX_IMAGEPOINTSERIES_H__D0E2A30A_3EB1_4114_9F52_4C4D06450CE0__INCLUDED_)
#define AFX_IMAGEPOINTSERIES_H__D0E2A30A_3EB1_4114_9F52_4C4D06450CE0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;
class CTeePicture;

/////////////////////////////////////////////////////////////////////////////
// CImagePointSeries wrapper class

class CImagePointSeries : public COleDispatchDriver
{
public:
	CImagePointSeries() {}		// Calls COleDispatchDriver default constructor
	CImagePointSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CImagePointSeries(const CImagePointSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPointer GetPointer();
	BOOL GetDark3D();
	void SetDark3D(BOOL bNewValue);
	long GetTransparency();
	void SetTransparency(long nNewValue);
	BOOL GetFastPoint();
	void SetFastPoint(BOOL bNewValue);
	long GetTreatNulls();
	void SetTreatNulls(long nNewValue);
	CTeePicture GetImagePoint();
	BOOL GetImageTransparent();
	void SetImageTransparent(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IMAGEPOINTSERIES_H__D0E2A30A_3EB1_4114_9F52_4C4D06450CE0__INCLUDED_)
