#if !defined(AFX_IPLOTLABELX_H__35B98814_1607_40D4_A4B0_7796AACF19C3__INCLUDED_)
#define AFX_IPLOTLABELX_H__35B98814_1607_40D4_A4B0_7796AACF19C3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CiPlotLabelX wrapper class

class CiPlotLabelX : public COleDispatchDriver
{
public:
	CiPlotLabelX() {}		// Calls COleDispatchDriver default constructor
	CiPlotLabelX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotLabelX(const CiPlotLabelX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetPopupEnabled();
	void SetPopupEnabled(BOOL bNewValue);
	BOOL GetHorizontal();
	void SetHorizontal(BOOL bNewValue);
	long GetZOrder();
	void SetZOrder(long nNewValue);
	double GetStartPercent();
	void SetStartPercent(double newValue);
	double GetStopPercent();
	void SetStopPercent(double newValue);
	double GetMarginLeft();
	void SetMarginLeft(double newValue);
	double GetMarginTop();
	void SetMarginTop(double newValue);
	double GetMarginRight();
	void SetMarginRight(double newValue);
	double GetMarginBottom();
	void SetMarginBottom(double newValue);
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	long GetAlignment();
	void SetAlignment(long nNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	unsigned long GetFontColor();
	void SetFontColor(unsigned long newValue);
	long GetWidth();
	long GetHeight();
	long GetLayer();
	void SetLayer(long nNewValue);
	BOOL GetUserSelected();
	void SetUserSelected(BOOL bNewValue);
	BOOL HitTest(long X, long Y);
	void DoEditMenuItemClick();
	BOOL GetUserCanEdit();
	void SetUserCanEdit(BOOL bNewValue);
	BOOL GetCanFocus();
	void SetCanFocus(BOOL bNewValue);
	void ImageLoadFromFile(LPCTSTR FileName);
	CPicture GetImage();
	void SetImage(LPDISPATCH newValue);
	void ImageClear();
	long GetImageListIndex();
	void SetImageListIndex(long nNewValue);
	long GetImageIndex();
	void SetImageIndex(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IPLOTLABELX_H__35B98814_1607_40D4_A4B0_7796AACF19C3__INCLUDED_)
