#if !defined(AFX_IPLOTANNOTATIONX_H__1CB8187F_10C2_4EC5_86C9_89A54BAD85E3__INCLUDED_)
#define AFX_IPLOTANNOTATIONX_H__1CB8187F_10C2_4EC5_86C9_89A54BAD85E3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CiPlotAnnotationX wrapper class

class CiPlotAnnotationX : public COleDispatchDriver
{
public:
	CiPlotAnnotationX() {}		// Calls COleDispatchDriver default constructor
	CiPlotAnnotationX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotAnnotationX(const CiPlotAnnotationX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetReference();
	void SetReference(long nNewValue);
	double GetX();
	void SetX(double newValue);
	double GetY();
	void SetY(double newValue);
	double GetX2();
	void SetX2(double newValue);
	double GetY2();
	void SetY2(double newValue);
	double GetWidth();
	void SetWidth(double newValue);
	double GetHeight();
	void SetHeight(double newValue);
	unsigned long GetPenColor();
	void SetPenColor(unsigned long newValue);
	long GetPenStyle();
	void SetPenStyle(long nNewValue);
	long GetPenWidth();
	void SetPenWidth(long nNewValue);
	unsigned long GetBrushColor();
	void SetBrushColor(unsigned long newValue);
	long GetBrushStyle();
	void SetBrushStyle(long nNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	CString GetChannelName();
	void SetChannelName(LPCTSTR lpszNewValue);
	unsigned long GetFontColor();
	void SetFontColor(unsigned long newValue);
	long GetTextRotation();
	void SetTextRotation(long nNewValue);
	BOOL GetUserCanMove();
	void SetUserCanMove(BOOL bNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetEnable();
	void SetEnable(BOOL bNewValue);
	BOOL GetUserCanSize();
	void SetUserCanSize(BOOL bNewValue);
	long PositionXToPixels(double Value);
	long PositionYToPixels(double Value);
	double PixelsXToPosition(long Value);
	double PixelsYToPosition(long Value);
	long GetImageIndex();
	void SetImageIndex(long nNewValue);
	long GetImageListIndex();
	void SetImageListIndex(long nNewValue);
	long GetTextHorzAlignment();
	void SetTextHorzAlignment(long nNewValue);
	long GetTextVertAlignment();
	void SetTextVertAlignment(long nNewValue);
	double GetTextHorzMargin();
	void SetTextHorzMargin(double newValue);
	double GetTextVertMargin();
	void SetTextVertMargin(double newValue);
	long GetLayer();
	void SetLayer(long nNewValue);
	BOOL GetUserSelected();
	void SetUserSelected(BOOL bNewValue);
	BOOL GetClipToAxes();
	void SetClipToAxes(BOOL bNewValue);
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	long GetOuterMargin();
	void SetOuterMargin(long nNewValue);
	BOOL HitTest(long X, long Y);
	long GetReferencePositionX();
	void SetReferencePositionX(long nNewValue);
	long GetReferencePositionY();
	void SetReferencePositionY(long nNewValue);
	long GetReferenceSizeX();
	void SetReferenceSizeX(long nNewValue);
	long GetReferenceSizeY();
	void SetReferenceSizeY(long nNewValue);
	long PolyPointAdd(double X, double Y);
	void PolyPointsClear();
	long GetPolyPointsCount();
	double GetPolyPointX(long Index);
	void SetPolyPointX(long Index, double newValue);
	double GetPolyPointY(long Index);
	void SetPolyPointY(long Index, double newValue);
	BOOL GetUserCanEdit();
	void SetUserCanEdit(BOOL bNewValue);
	BOOL GetCanFocus();
	void SetCanFocus(BOOL bNewValue);
	long GetClickRectLeft();
	long GetClickRectRight();
	long GetClickRectTop();
	long GetClickRectBottom();
	CPicture GetImage();
	void SetImage(LPDISPATCH newValue);
	void ImageClear();
	void ImageLoadFromFile(LPCTSTR FileName);
	BOOL GetSelectModeOnlyInteraction();
	void SetSelectModeOnlyInteraction(BOOL bNewValue);
	long GetTextLineAlignment();
	void SetTextLineAlignment(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IPLOTANNOTATIONX_H__1CB8187F_10C2_4EC5_86C9_89A54BAD85E3__INCLUDED_)
